#!/usr/bin/env python3
"""Generate chapter stubs and _quarto.yml from outline/chapters.yml.

Single source of truth is outline/chapters.yml. Running this script:
  * writes chapters/NN-slug.qmd stubs (skips files that already exist, so
    written prose is never clobbered; use --force to overwrite stubs),
  * writes appendices/<id>-slug.qmd stubs,
  * regenerates _quarto.yml with the validated Persian/RTL toolchain config
    (LuaLaTeX + babel bidi=basic for PDF; cosmo + custom.scss for HTML).

Usage:
  python tools/gen_stubs.py            # generate missing stubs + _quarto.yml
  python tools/gen_stubs.py --force    # also overwrite existing chapter stubs
"""
from __future__ import annotations
import argparse
import os
import sys

try:
    import yaml
except ImportError:
    sys.exit("PyYAML is required: pip install pyyaml")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUTLINE = os.path.join(ROOT, "outline", "chapters.yml")
CHAPTERS_DIR = os.path.join(ROOT, "chapters")
APPENDICES_DIR = os.path.join(ROOT, "appendices")
QUARTO_YML = os.path.join(ROOT, "_quarto.yml")


def load_outline():
    with open(OUTLINE, encoding="utf-8") as fh:
        return yaml.safe_load(fh)


def chapter_filename(ch):
    return f"{ch['n']:02d}-{ch['slug']}.qmd"


def chapter_stub(ch, num_to_title):
    """Return the .qmd stub text for one chapter."""
    prereqs = ch.get("prereqs") or []
    if prereqs:
        links = "، ".join(
            f"[{num_to_title.get(p, p)}](../chapters/{p:02d}-*.qmd)" for p in prereqs
        )
        prereq_line = f"**پیش‌نیازها:** فصل‌های {', '.join(str(p) for p in prereqs)}"
    else:
        prereq_line = "**پیش‌نیازها:** ندارد (نقطهٔ شروع)"

    objectives = ch.get("objectives") or []
    obj_comment = "\n".join(f"  - {o}" for o in objectives)
    flags = ", ".join(ch.get("flags") or [])

    return f"""---
title: "{ch['title_fa']}"
---

<!--
  PLANNING METADATA (author-facing; not rendered)
  chapter      : {ch['n']}
  title_en     : {ch['title_en']}
  est_pages    : {ch.get('pages', '?')}
  content_flags: {flags}
  objectives (translate/expand into the callout below):
{obj_comment}
-->

::: {{.callout-note}}
## اهداف یادگیری
<!-- TODO: نگارش اهداف یادگیری به فارسی بر اساس فهرست بالا. -->
:::

{prereq_line}

## درآمد

<!-- TODO: متن این فصل نوشته شود. پرچم‌های محتوا: {flags} -->

## بدنهٔ فصل

<!-- TODO -->

## جمع‌بندی

<!-- TODO -->

## پرسش‌ها و تمرین‌ها

<!-- TODO: مفهومی / استدلالی / محاسباتی / شبیه‌سازی / طراحی‑ساخت.
     پاسخ‌ها در پیوست «کلید پاسخ‌ها» تجمیع می‌شوند. -->
"""


def appendix_stub(ap):
    return f"""---
title: "{ap['title_fa']}"
---

<!-- title_en: {ap['title_en']} -->

<!-- TODO -->
"""


def write_if_needed(path, content, force):
    if os.path.exists(path) and not force:
        return False
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(content)
    return True


# --- _quarto.yml template (validated config from the smoke test) -------------
QUARTO_HEAD = """# =====================================================================
#  GENERATED by tools/gen_stubs.py from outline/chapters.yml — DO NOT EDIT
#  the chapter list by hand. Edit the outline and re-run the generator.
#
#  Validated Persian/RTL toolchain:
#    * PDF : LuaLaTeX + babel (bidi=basic), fonts/Vazirmatn via theme/preamble.tex
#    * HTML: cosmo + theme/custom.scss, dir=rtl/lang=fa, LTR islands via ltr.lua
#  NOTE: do NOT set a global `lang:` — it makes Pandoc load babel/polyglossia
#  for PDF and clashes with our preamble. `lang`/`dir` are set on html only.
# =====================================================================
project:
  type: book
  output-dir: _book

book:
  title: "{title_fa}"
  subtitle: "{subtitle_fa}"
  author: "{author}"
  cover-image: cover/cover.png      # HTML/EPUB cover (PDF cover via \\AtBeginDocument in theme/preamble.tex)
  search: true
  chapters:
    - index.qmd
"""

QUARTO_TAIL = """
bibliography: references/refs.bib

filters:
  - theme/ltr.lua

format:
  html:
    lang: fa
    dir: rtl
    theme:
      - cosmo
      - theme/custom.scss
    include-in-header: theme/mathjax-config.html
    toc: true
    toc-title: "فهرست"
    number-sections: true
    code-copy: true
    code-overflow: wrap
  pdf:
    pdf-engine: lualatex
    documentclass: scrreport
    include-in-header: theme/preamble.tex
    toc: true
    toc-depth: 2          # Quarto book maps toc-depth:N -> LaTeX tocdepth N-1;
                          # 2 => tocdepth 1 => ToC lists chapters + sections only
                          # (subsections hidden) to keep the PDF ToC compact.
    number-sections: true
    colorlinks: true
    code-overflow: wrap
"""


def build_quarto_yml(outline):
    book = outline["book"]
    lines = [QUARTO_HEAD.format(
        title_fa=book["title_fa"],
        subtitle_fa=book.get("subtitle_fa", ""),
        author=book.get("author", "—"),
    )]
    for vol in outline["volumes"]:
        part_title = f"جلد {vol['id']} — {vol['title_fa']}"
        lines.append(f'    - part: "{part_title}"')
        lines.append(f"      chapters:")
        for ch in vol["chapters"]:
            lines.append(f"        - chapters/{chapter_filename(ch)}")
    # appendices
    apps = outline.get("appendices") or []
    if apps:
        lines.append("  appendices:")
        for ap in apps:
            lines.append(f"    - appendices/{ap['id']}-{ap['slug']}.qmd")
    lines.append(QUARTO_TAIL)
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--force", action="store_true",
                        help="overwrite existing chapter/appendix stubs")
    args = parser.parse_args()

    outline = load_outline()
    os.makedirs(CHAPTERS_DIR, exist_ok=True)
    os.makedirs(APPENDICES_DIR, exist_ok=True)

    num_to_title = {}
    for vol in outline["volumes"]:
        for ch in vol["chapters"]:
            num_to_title[ch["n"]] = ch["title_fa"]

    written, skipped = 0, 0
    for vol in outline["volumes"]:
        for ch in vol["chapters"]:
            path = os.path.join(CHAPTERS_DIR, chapter_filename(ch))
            if write_if_needed(path, chapter_stub(ch, num_to_title), args.force):
                written += 1
            else:
                skipped += 1

    for ap in outline.get("appendices") or []:
        path = os.path.join(APPENDICES_DIR, f"{ap['id']}-{ap['slug']}.qmd")
        if write_if_needed(path, appendix_stub(ap), args.force):
            written += 1
        else:
            skipped += 1

    with open(QUARTO_YML, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(build_quarto_yml(outline))

    n_ch = sum(len(v["chapters"]) for v in outline["volumes"])
    print(f"Outline: {len(outline['volumes'])} volumes, {n_ch} chapters, "
          f"{len(outline.get('appendices') or [])} appendices.")
    print(f"Stubs written: {written}, skipped (already exist): {skipped}.")
    print(f"Wrote {QUARTO_YML}.")


if __name__ == "__main__":
    main()
